/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archivocancion;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fing.labcom
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public boolean estadoDesarrollo=true;
    public static String directorio;
    public static String nombreArchivoTexto="cancion1.txt";
    public Principal() {
        this.setTitle("      CAMBIO DE LETRA DE LA CANCION ");
        if(estadoDesarrollo==true){
            directorio=System.getProperty("user.dir");
        }else{
            directorio=System.getProperty("java.class.path");
            File dir= new File(directorio);
            directorio=dir.getParent();
        }
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnabrir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncambiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmostrar = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnabrir.setText("Abrir");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncambiar.setText("Cambiar");
        btncambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiarActionPerformed(evt);
            }
        });

        txtmostrar.setColumns(20);
        txtmostrar.setRows(5);
        jScrollPane1.setViewportView(txtmostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btncambiar)
                        .addGap(50, 50, 50)
                        .addComponent(btnguardar)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnabrir)
                    .addComponent(btncambiar)
                    .addComponent(btnguardar))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
       String texto; //Variable para guardar la lectura
       txtmostrar.setText(""); //Limpiamos el JtextArea antes de comenzar
       try{
           //declaramos la variable archivo como un objeto File
           //y le asignamos una ruta donde se creara
           File archivo = new File(directorio+"/"+nombreArchivoTexto);
           //BufferedReader ayuda a manejar las lecturas de streams
           //FileReader mos ayuda a mirar dentro del archivo
           BufferedReader br=new BufferedReader(new FileReader(archivo));
           //verificamos dentro del archivo hasta finalizarlo
           if(archivo.exists()){
               while((texto=br.readLine())!=null){
                   //Cada linea del archivo al JtextArea
                   txtmostrar.append(texto+"\n");
               }
           }
           
       } catch (IOException ioe) {
           JOptionPane.showMessageDialog(rootPane, "Error al abrir el archivo");
            
        }
    }//GEN-LAST:event_btnabrirActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
      String ArchivoTexto="cancion.txt";
      try{
          File archivo =new File(directorio+"/"+ArchivoTexto);
          if(!archivo.exists()){
              //BufferedWriter ayuda a manejar los streams
              //FileWriter nos ayuda a escribir dentro del archivo
              
              BufferedWriter bw= new BufferedWriter(new FileWriter(archivo));
              //usamos el metodo .write para escribir la cadena
              bw.write(txtmostrar.getText());
              //Muy importante, siempre cerrar el archivo
              bw.close();
              txtmostrar.setText(""); //Limpiamos elJTextArea 
              JOptionPane.showMessageDialog(rootPane, "Archivo guardado con éxito");
          }
      } catch (IOException e1) {
          JOptionPane.showMessageDialog(rootPane, "Error al guardar en el archivo");
          
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiarActionPerformed
        String can;
        can=txtmostrar.getText();  //Obtenemos el texto del JTextArea
        char cadena[]=new char[can.length()];
        txtmostrar.setText("");//Limpiamos el JTextArea
        for (int i = 0; i < cadena.length; i++) {
            //ciclo para ingreso de valores
            cadena[i]= can.charAt(i);
        }
        for (int i = 0; i < cadena.length; i++) {
            //ciclo para evaluar la cadena
            if(cadena[i]=='a')
            {
                cadena[i]='e'; //se asigna la letra e por a
                
            }
        can= ""+ cadena[i];
        txtmostrar.append(can);
        }
    }//GEN-LAST:event_btncambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btncambiar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtmostrar;
    // End of variables declaration//GEN-END:variables
}
