/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.Insert;
import dominio.Ordenamiento;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import validaciones.ValueInt;

/**
 *
 * @author danni
 */
public class Home extends javax.swing.JFrame {

    int min;
    int max;
    int tam;
    int[] array;
    Ordenamiento o;
    String b;
    Insert in;
    ValueInt intv;
    IngresoManual inmanu;
    long startTime;
    long endTime;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        novisibleAleatorio();
        o = new Ordenamiento();
        in = new Insert();
        intv = new ValueInt();
        inmanu = new IngresoManual();
    }

    public void novisibleAleatorio() {
        txtMax.setEnabled(false);
        txtMin.setEnabled(false);
        jtamanio.setEnabled(false);
        jButton1.setEnabled(false);
        jComboBox2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
//        jLabel4.setVisible(false);
//        lblMax.setVisible(false);
//        lblMin.setVisible(false);
//        lblvalores.setVisible(false);

    }

    public void visibleAleatorio() {
        txtMax.setEnabled(true);
        txtMin.setEnabled(true);
        lblMax.setVisible(true);
        lblMin.setVisible(true);
        lblvalores.setVisible(true);
        jtamanio.setEnabled(true);
        jButton1.setEnabled(true);
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtamanio = new javax.swing.JTextField();
        lblvalores = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tiemponanos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ". . .", "Aleatorio", "Manual" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingreso de vector");

        jLabel2.setText("Tamaño del Vector");

        jtamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtamanioActionPerformed(evt);
            }
        });
        jtamanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtamanioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtamanioKeyTyped(evt);
            }
        });

        lblvalores.setText("Valores");

        lblMin.setText("Desde");

        lblMax.setText("Hasta");

        txtMin.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMinKeyPressed(evt);
            }
        });

        txtMax.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });
        txtMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaxKeyPressed(evt);
            }
        });

        jLabel4.setText("Ingreso Manual");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setText("Como desea ordenar");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ". . .", "Bubblesort", "Selectsort", "Insertsort", "Shellsort", "Quicksort", "Mergesort" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Llenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Imprimir ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Algoritmos de Ordenamiento");

        jLabel6.setText("Tiempo de Ejecución");

        tiemponanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiemponanosActionPerformed(evt);
            }
        });

        jLabel7.setText("nanosegundos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(123, 266, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lblMin)
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(lblMax))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblvalores)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiemponanos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblvalores))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMin)
                            .addComponent(lblMax))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiemponanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(90, 90, 90))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        if (jComboBox1.getSelectedItem().equals("Aleatorio")) {
            switch (jComboBox2.getSelectedIndex()) {
                case 0:
                    System.out.println("elija una");
                    break;
                case 1:

                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.burbujaOptimizada(in.getTempBubble());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempBubble()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;

                case 2:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.InsertionSort(in.getTempSelect());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempSelect()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;

                case 3:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.seleccion(in.getTempInser());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempInser()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 4:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.shellSort(in.getTempShell());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempShell()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 5:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.quicksort(in.getTempQuick(), 0, in.getTempQuick().length - 1);
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempQuick()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 6:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    Ordenamiento.ordenacionMergeSort(in.getTempMerge());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getTempMerge()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;

            }
        } else if (jComboBox1.getSelectedItem().equals("Manual")) {
            switch (jComboBox2.getSelectedIndex()) {
                case 0:
                    System.out.println("elija una");
                    break;
                case 1:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.burbujaOptimizada(in.getManualBubble());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getManualBubble()));
                    tiemponanos.setText(String.valueOf(endTime));

                    break;

                case 2:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.InsertionSort(in.getManualSelect());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirManual(in.getManualSelect()));
                    tiemponanos.setText(String.valueOf(endTime));

                    break;

                case 3:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.seleccion(in.getManualInser());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirManual(in.getManualInser()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 4:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.shellSort(in.getManualShell());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirManual(in.getManualShell()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 5:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    o.quicksort(in.getManualQuick(), 0, in.getManualQuick().length - 1);
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(in.getManualQuick()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;
                case 6:
                    jTextArea2.setText("");
                    startTime = System.nanoTime();
                    Ordenamiento.ordenacionMergeSort(Insert.getManualMerge());
                    endTime = System.nanoTime() - startTime;
                    jTextArea2.append(in.imprimirAleatorio(Insert.getManualMerge()));
                    tiemponanos.setText(String.valueOf(endTime));
                    break;

            }
        } else {
            System.out.println("Elija una opcion");
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
        //String seleccion = (String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        if (ValueInt.isNumeric(txtMax.getText()) && ValueInt.isNumeric(txtMin.getText()) && ValueInt.isNumeric(jtamanio.getText())) {
            min = Integer.parseInt(txtMin.getText());
            max = Integer.parseInt(txtMax.getText());
            tam = Integer.parseInt(jtamanio.getText());

            //(int) Math.random();
            if (min < max) {
                //aqui va metodo inestrar

                in.crearArrayAleatorio(tam, max, min);

                jTextArea1.append(in.imprimirAleatorio(in.getArray()));

            } else {
                System.out.println("Ingrese intervalos correctos");
            }
            jComboBox2.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese enteros");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void jtamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtamanioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBox1.getSelectedItem();

        if (seleccion.equals("Aleatorio")) {
            jTextArea1.setText("");
            jTextArea2.setText("");
            visibleAleatorio();
            jButton2.setEnabled(false);

        } else if (seleccion.equals("Manual")) {
            jTextArea1.setText("");
            jTextArea2.setText("");
            novisibleAleatorio();
            jButton2.setEnabled(true);
        } else {
            novisibleAleatorio();
        }
        System.out.println("Elija una opcion");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jtamanioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtamanioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((jtamanio.getText()).equals("")) {
                JOptionPane.showMessageDialog(null, "Llenar el Campo");

            } else {
                jtamanio.grabFocus();
            }
        }
    }//GEN-LAST:event_jtamanioKeyPressed

    private void txtMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((txtMin.getText()).equals("")) {
                JOptionPane.showMessageDialog(null, "Llenar el Campo");

            } else {
                txtMin.grabFocus();
            }
        }
    }//GEN-LAST:event_txtMinKeyPressed

    private void txtMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((txtMax.getText()).equals("")) {
                JOptionPane.showMessageDialog(null, "Llenar el Campo");

            } else {
                txtMax.grabFocus();
            }
        }
    }//GEN-LAST:event_txtMaxKeyPressed

    private void jtamanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtamanioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jtamanioKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jTextArea2.setText("");
        inmanu.setVisible(true);
        jButton3.setEnabled(true);
        jButton2.setEnabled(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jTextArea1.setText("");
        jTextArea1.append(in.imprimirManual1(in.getManu()));
        jButton2.setEnabled(true);

        jButton3.setEnabled(false);
        jComboBox2.setEnabled(true);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void tiemponanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiemponanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiemponanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jtamanio;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblvalores;
    private javax.swing.JTextField tiemponanos;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    // End of variables declaration//GEN-END:variables
}
