/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domnio.Usuarios;
import guiPanel.CambiaPanel;
import domnio.GestorUsuarios;
import data.Archivos;
import domnio.Contactos;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author danni
 */
public class Registrarse extends javax.swing.JFrame {

    Usuarios user;
    GestorUsuarios gest;
    Archivos arc;
    static ArrayList<Contactos> con;
    /**
     * Creates new form Registrarse
     */
    static {
            con=new ArrayList<>();
    }
    public Registrarse() {
        initComponents();
        setLocationRelativeTo(null);
        gest=new GestorUsuarios();
        arc=new Archivos();
    
        
    }

    public static ArrayList<Contactos> getCon() {
        return con;
    }

    public static void setCon(ArrayList<Contactos> con) {
        Registrarse.con = con;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jcorreo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jpass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpass1 = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        iconoima = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 34, 88));
        jLabel4.setText("Registro");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Anadir Imagen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        juser.setBackground(new java.awt.Color(16, 16, 16));
        juser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        juser.setForeground(new java.awt.Color(78, 34, 88));
        juser.setText("Ingrese el Nombre");
        juser.setBorder(null);
        juser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juserMouseClicked(evt);
            }
        });
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        jPanel1.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 290, 40));

        jSeparator2.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator2.setForeground(new java.awt.Color(78, 34, 88));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 290, 20));

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jcorreo.setBackground(new java.awt.Color(16, 16, 16));
        jcorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcorreo.setForeground(new java.awt.Color(78, 34, 88));
        jcorreo.setText("Ingrese el Correo");
        jcorreo.setBorder(null);
        jcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcorreoMouseClicked(evt);
            }
        });
        jcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 290, 40));

        jSeparator7.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator7.setForeground(new java.awt.Color(78, 34, 88));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, 20));

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contrasena");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jpass.setBackground(new java.awt.Color(16, 16, 16));
        jpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpass.setForeground(new java.awt.Color(78, 34, 88));
        jpass.setText("jPasswordField1");
        jpass.setBorder(null);
        jpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpassMouseClicked(evt);
            }
        });
        jPanel1.add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 290, 40));

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Repita Contrasena");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator4.setForeground(new java.awt.Color(78, 34, 88));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 290, 20));

        jpass1.setBackground(new java.awt.Color(16, 16, 16));
        jpass1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpass1.setForeground(new java.awt.Color(78, 34, 88));
        jpass1.setText("jPasswordField1");
        jpass1.setBorder(null);
        jpass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpass1MouseClicked(evt);
            }
        });
        jPanel1.add(jpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 290, 40));

        jSeparator6.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator6.setForeground(new java.awt.Color(78, 34, 88));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 290, 20));

        iconoima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        iconoima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        iconoima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(iconoima, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 140, 210));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombres");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mail.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 440, 410));

        jPanel3.setBackground(new java.awt.Color(78, 34, 88));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Registrarse");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 180, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juserMouseClicked
        // TODO add your handling code here:
        juser.setText("");
    }//GEN-LAST:event_juserMouseClicked

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void jcorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcorreoMouseClicked
        // TODO add your handling code here:
        jcorreo.setText("");
    }//GEN-LAST:event_jcorreoMouseClicked

    private void jcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcorreoActionPerformed

    private void jpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpassMouseClicked
        // TODO add your handling code here:
        jpass.setText("");
    }//GEN-LAST:event_jpassMouseClicked

    private void jpass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpass1MouseClicked
        // TODO add your handling code here:
        jpass1.setText("");
    }//GEN-LAST:event_jpass1MouseClicked

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        jPanel3.setBackground(new java.awt.Color(54, 6, 55));
    }//GEN-LAST:event_jPanel3MouseMoved

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

       
        String nombre = juser.getText();
        String correo = jcorreo.getText();
        String pass1 = new String(jpass.getPassword());
        String pass2 = new String(jpass1.getPassword());
        Boolean ver = false;
        if (pass1.equals(pass2)!=true) {
          //  jpass1.setText("");
            System.out.println("Contrasenas no coinciden");
        }else{
            user = new Usuarios(nombre, correo, pass1,con);
            gest.addUser(user);
            try {
                arc.guardarDatos();
            } catch (IOException ex) {
                System.out.println("No se pudo guardar");
            }
            this.dispose();
            new Login().setVisible(true);
            
        }


    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new java.awt.Color(78, 34, 88));
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconoima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jcorreo;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
