/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiPanel;

import domnio.Contactos;
import domnio.Correo;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import guiPanel.Jptres;
/**
 *
 * @author danni
 */
public class Enviado extends javax.swing.JPanel {

    /**
     * Creates new form Enviado
     */
    public Enviado() {
        initComponents();
        CrearModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajesText = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correos Enviados");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 58, 320, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        mensajesText.setBackground(new java.awt.Color(0, 0, 0));
        mensajesText.setColumns(20);
        mensajesText.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        mensajesText.setForeground(new java.awt.Color(255, 255, 255));
        mensajesText.setRows(5);
        jScrollPane2.setViewportView(mensajesText);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 450, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int r=Jptres.getCorreo().size();
        Correo o[] = new Correo[r];
        int i=0;
        for ( i = 0; i < r; i++) {
            Correo c = (Correo)(Jptres.getCorreo().get(i));
            M.addRow(o);
            M.setValueAt(c.getUsuarioCorreo(), i, 0);
            M.setValueAt(c.getAsunto(), i, 1);
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         mensajesText.setText("");
         int fila = jTable1.rowAtPoint(evt.getPoint());
         int columna = jTable1.columnAtPoint(evt.getPoint());
        //int numero = 0;
         if ((fila > -1) && (columna > -1)){
              System.out.println(fila);
           //  numero= M.getValueAt(fila, columna);
             Correo c = (Correo)(Jptres.getCorreo().get(fila));
             String mensaje=c.getMensaje();
             mensajesText.append(mensaje);
             
         }
        
        
    }//GEN-LAST:event_jTable1MouseClicked
  DefaultTableModel M;

    public void CrearModelo() {
        try {
            M = (new DefaultTableModel(null, new String[]{"Correo", "Asunto"}));
            
            jTable1.setModel(M);
        } catch (Exception e) {

        }
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea mensajesText;
    // End of variables declaration//GEN-END:variables
}
