/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiPanel;

import com.sun.javafx.embed.AbstractEvents;
import domnio.Controlador;
import domnio.Correo;
import gui.Login;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author danni
 */
public class Jptres extends javax.swing.JPanel {

    String ruta;
    Correo c = new Correo();
    String nombreRu;
    MouseEvent evento;
    static ArrayList<Correo> correo;
     static ArrayList<Correo> borrador;
     Login l;

    static {
        correo = new ArrayList<>();
        borrador = new ArrayList<>();
    }

    /**
     * Creates new form Jptres
     */
    public Jptres() {
        initComponents();
        ruta = "";
        l=new Login();
        jFrom.setText("");
        jMensaje.setText("");
       
        jLabel9.setText( l.getNombre());
    }

    public void enviarCorreo() {
        c.setPassword("halo1723463053");
        c.setUsuarioCorreo("dannirux@gmail.com");
        c.setAsunto(jAsunto.getText());
        c.setMensaje(jMensaje.getText());
        c.setDestino(jFrom.getText().trim());
        c.setNombreArchivo(nombreRu);
        c.setRutaArchivo(ruta);

        Controlador co = new Controlador();
        if (co.enviarCorreo(c)) {
            JOptionPane.showMessageDialog(null, "Enviado");
        } else {
            JOptionPane.showMessageDialog(null, "Vuelva a Intentarlo");
        }

    }

    public static ArrayList<Correo> getCorreo() {
        return correo;
    }

    public static void setCorreo(ArrayList<Correo> correo) {
        Jptres.correo = correo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jAsunto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMensaje = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 187, 187));
        jLabel3.setText(" X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 32, 35));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 187, 187));
        jLabel2.setText("--");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 32, 35));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("De:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 59, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Para:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 106, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 93, 886, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 139, 886, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 191, 886, 10));

        jAsunto.setBackground(new java.awt.Color(51, 51, 51));
        jAsunto.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jAsunto.setForeground(new java.awt.Color(204, 204, 204));
        jAsunto.setText("Asunto..");
        jAsunto.setBorder(null);
        jAsunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAsuntoMouseClicked(evt);
            }
        });
        jAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsuntoActionPerformed(evt);
            }
        });
        add(jAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 890, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/upload.png"))); // NOI18N
        jLabel6.setText("Adjuntar Archivo");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Negrita");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cursiva");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 30));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bold.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 50));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/italic.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 60, 50));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Normal");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/letter-n.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 960, 60));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMensaje.setBackground(new java.awt.Color(51, 51, 51));
        jMensaje.setColumns(20);
        jMensaje.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jMensaje.setRows(5);
        jScrollPane1.setViewportView(jMensaje);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 960, 410));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Nuevo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/send.png"))); // NOI18N
        jLabel7.setText("Enviar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 90, 50));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        jLabel8.setText("Descartar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 110, 50));

        jFrom.setBackground(new java.awt.Color(51, 51, 51));
        jFrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFrom.setForeground(new java.awt.Color(255, 255, 255));
        jFrom.setBorder(null);
        jFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFromActionPerformed(evt);
            }
        });
        add(jFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 730, 40));

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 330, 30));

        jScrollPane2.setViewportView(jEditorPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_OPTION;

        int result = JOptionPane.showConfirmDialog(null, "Seguro desea salir?", "Cerrar", dialog, JOptionPane.WARNING_MESSAGE);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //  this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAsuntoActionPerformed

    private void jAsuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAsuntoMouseClicked
        // TODO add your handling code here:
        jAsunto.setText("");
    }//GEN-LAST:event_jAsuntoMouseClicked

    private void jFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFromActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        // 

        if ((jFrom.getText().equals("") || jMensaje.getText().equals("") || jAsunto.getText().equals(""))) {
            System.out.println("vacio");
        } else {
            System.out.println("lleno");
//            String texto = "";
//            texto += "Para:   " + jFrom.getText();
//            texto += "Asunto: " + jAsunto.getText();
//            texto += "Mensaje: \n" + jMensaje.getText();
            correo.add(new Correo(jFrom.getText(),jAsunto.getText(),jMensaje.getText()));
            enviarCorreo();
        }

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Archivo Adjunto");
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = fc.getSelectedFile().toString();
            nombreRu = fc.getName(new File(ruta));
            jLabel6.setText(ruta);

        } else {
            ruta = "";
            nombreRu = "";
            jLabel6.setText("Vacio");
        }
        if ((ruta == "")) {
            ruta = "";
            nombreRu = "";
            jLabel6.setText("Vacio");

        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here
          if ((jFrom.getText().equals("") || jMensaje.getText().equals("") || jAsunto.getText().equals(""))) {
            System.out.println("vacio");
        } else {
            System.out.println("lleno");
//            String texto = "";
//            texto += "Para:   " + jFrom.getText();
//            texto += "Asunto: " + jAsunto.getText();
//            texto += "Mensaje: \n" + jMensaje.getText();
            borrador.add(new Correo(jFrom.getText(),jAsunto.getText(),jMensaje.getText()));
        }

        
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        
        int negrita=Font.BOLD;
        int ital=Font.ITALIC;
        int normal=Font.PLAIN;
        int fondo=Font.BOLD;
        
        Font f= new Font("DialogInput", negrita, 18); // Nombre, Estilo, Tamaño
jMensaje.setFont(f);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
                Font f= new Font("DialogInput", Font.ITALIC, 18); // Nombre, Estilo, Tamaño
jMensaje.setFont(f);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Font f= new Font("DialogInput", Font.PLAIN, 18); // Nombre, Estilo, Tamaño
jMensaje.setFont(f);
    }//GEN-LAST:event_jLabel15MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAsunto;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
