/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.ventanas;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author danni
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
            this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novato = new javax.swing.JButton();
        Intermedio = new javax.swing.JButton();
        Experto = new javax.swing.JButton();
        Nutricion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Novato.setBackground(new java.awt.Color(102, 255, 255));
        Novato.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Novato.setText("Novato");
        Novato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovatoMouseClicked(evt);
            }
        });
        Novato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovatoActionPerformed(evt);
            }
        });
        getContentPane().add(Novato, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, 80));

        Intermedio.setBackground(new java.awt.Color(255, 255, 51));
        Intermedio.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Intermedio.setText("Intermedio");
        Intermedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntermedioMouseClicked(evt);
            }
        });
        getContentPane().add(Intermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 290, 80));

        Experto.setBackground(new java.awt.Color(255, 0, 0));
        Experto.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Experto.setText("Experto");
        Experto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpertoMouseClicked(evt);
            }
        });
        Experto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertoActionPerformed(evt);
            }
        });
        getContentPane().add(Experto, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 230, 80));

        Nutricion.setBackground(new java.awt.Color(102, 255, 51));
        Nutricion.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Nutricion.setText("Nutricion");
        Nutricion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutricionActionPerformed(evt);
            }
        });
        getContentPane().add(Nutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 280, 80));

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 100)); // NOI18N
        jLabel2.setText("B-LIGHT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\danni\\OneDrive\\Fotos\\LIVIANO.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 380, 270));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\danni\\OneDrive\\Fotos\\INTERMEDIO.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 290, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\danni\\OneDrive\\Fotos\\EXPERTO.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 260, 240));

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setText("x");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danni\\OneDrive\\Fotos\\sin excusas.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 629));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NutricionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutricionActionPerformed
           Nutricion xd =new Nutricion();
           xd.setVisible(true);
           
    }//GEN-LAST:event_NutricionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void NovatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovatoActionPerformed
      
    }//GEN-LAST:event_NovatoActionPerformed

    private void NovatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovatoMouseClicked
         novato menu1 =new novato();
           menu1.setVisible(true);
           
        
        
        
    }//GEN-LAST:event_NovatoMouseClicked

    private void IntermedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntermedioMouseClicked
         Intermedio menu2 =new Intermedio();
           menu2.setVisible(true);
           
        
        
    }//GEN-LAST:event_IntermedioMouseClicked

    private void ExpertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpertoMouseClicked
         experto menu3 =new experto();
           menu3.setVisible(true);
           
        
        
    }//GEN-LAST:event_ExpertoMouseClicked

    private void ExpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertoActionPerformed
      
    }//GEN-LAST:event_ExpertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Experto;
    private javax.swing.JButton Intermedio;
    private javax.swing.JButton Novato;
    private javax.swing.JButton Nutricion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
