/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import datos.Archivos;
import dominio.CruzRoja;
import java.io.IOException;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import dominio.Donante;

/**
 *
 * @author danni
 */
public class BEspecifica extends javax.swing.JFrame {
//private Donante d;
private Archivos a;
private CruzRoja c;
    /**
     * Creates new form bEspecifica
     */
    public BEspecifica() {
        initComponents();
        this.setLocationRelativeTo(null);
        a=new Archivos();
        c=new CruzRoja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpos = new javax.swing.JTextField();
        jnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jbusca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbusca1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Multiply_32px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 60, 20));

        jpos.setBorder(null);
        jpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jposActionPerformed(evt);
            }
        });
        jPanel1.add(jpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 40, 30));

        jnombre.setBorder(null);
        jnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });
        jPanel1.add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 460, 30));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        area.setRows(5);
        area.setBorder(null);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 750, 340));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("Donante a Buscar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jbusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Search_32px_2.png"))); // NOI18N
        jbusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuscaMouseClicked(evt);
            }
        });
        jPanel1.add(jbusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 60, 50));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 60, 40));

        jbusca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbusca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Search_32px_2.png"))); // NOI18N
        jbusca1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbusca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbusca1MouseClicked(evt);
            }
        });
        jPanel1.add(jbusca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 70, 70));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel4.setText("Posicion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/google.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -20, -1, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreActionPerformed

    private void jbuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscaMouseClicked
  
        CruzRoja.getDonantes();
        String nombre =new String(jnombre.getText());
        String m=   c.buscarPorNombre(nombre);
    
        
        area.append(m);
        
    }//GEN-LAST:event_jbuscaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
          try {
        // TODO add your handling code here:
        a.leerArchivos();
        JOptionPane.showMessageDialog(null, "Se ha leido correctamente el archivo");
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null,"No se ha podido leer el archivo");
    } catch (ClassNotFoundException ex) {
        
    }
        String nombre =new String(jnombre.getText());
        String m=   a.buscarPorNombreArchivo(nombre);
   area.append(m);
   
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jbusca1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbusca1MouseClicked
        // TODO add your handling code here:
         CruzRoja.getDonantes();
         try{
        Integer id1 =new Integer(jpos.getText());
        Integer id= id1-1;
        String m= c.buscarPorId(id);
           jpos.setText(null);
        area.append(m);
         }catch(InputMismatchException ex){
                  System.out.println("Ingrese una pocision valida");
                   
              }
        
        
    }//GEN-LAST:event_jbusca1MouseClicked

    private void jposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jposActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Home h=new Home();
        h.setVisible(true);

    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BEspecifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jbusca;
    private javax.swing.JLabel jbusca1;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jpos;
    // End of variables declaration//GEN-END:variables
}
