/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.CruzRoja;
import dominio.Donante;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import datos.Archivos;
import util.Validacion;

/**
 *
 * @author danni
 */
public class GestionarDonante extends javax.swing.JFrame {

    private CruzRoja r;
    private Donante d;
    private Archivos a;
    private Validacion v;

    /**
     * Creates new form GestionarDonante
     */
    public GestionarDonante() {
        initComponents();
        this.setLocationRelativeTo(null);
        r = new CruzRoja();
        a=new Archivos();
        v=new Validacion();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jedad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        selector = new javax.swing.JComboBox<>();
        jsangre = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbutonguardar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setText("Edad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de Sangre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jnombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jnombre.setBorder(null);
        jnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jnombreMouseExited(evt);
            }
        });
        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });
        getContentPane().add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, 30));

        jedad.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jedad.setBorder(null);
        jedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jedadActionPerformed(evt);
            }
        });
        getContentPane().add(jedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel6.setText("Nuevo Donante");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 650, 200));

        selector.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        selector.setBorder(null);
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });
        getContentPane().add(selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 30));

        jsangre.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jsangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O RH+", "O RH-", "A RH+", "A RH-", "B RH+", "B RH-", "AB RH+", "AB RH-" }));
        getContentPane().add(jsangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 140, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, 10));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Multiply_32px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, -20, 70, 80));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel7.setText("Guardar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, -1, -1));

        jbutonguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save.png"))); // NOI18N
        jbutonguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutonguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutonguardarMouseClicked(evt);
            }
        });
        getContentPane().add(jbutonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 60, 20));

        jpos.setBorder(null);
        jpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jposActionPerformed(evt);
            }
        });
        getContentPane().add(jpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 40, 30));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel8.setText("Posicion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/refresh-button.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/new-user.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/list-button.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, 60));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/gestion.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreActionPerformed

    private void jedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jedadActionPerformed

    private void jnombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnombreMouseExited
        // TODO add your handling code here:
        area.setText("");
    }//GEN-LAST:event_jnombreMouseExited

    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        // TODO add your handling code here:
  
        
        
        
    }//GEN-LAST:event_selectorActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
       // this.setState(Home.ICONIFIED);
        this.dispose();
        Home h=new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jbutonguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutonguardarMouseClicked
        try {
            a.guardarDatos();
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR");
        }
        
        
        
    }//GEN-LAST:event_jbutonguardarMouseClicked

    private void jposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jposActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
       String name=new String(jnombre.getText());
        r.borrar(name);
        
        
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        try{               
        String nombre = new String(jnombre.getText());
        String edad = new String(jedad.getText());
        
        int edad1 = Integer.parseInt(edad);
        v.vEdad(edad1);
        
          String sexo = selector.getSelectedItem().toString();  
          if(sexo=="Masculino"){
              sexo="H";
          }else if(sexo=="Femenino"){
              sexo="F";
          }
           String boxsangre = jsangre.getSelectedItem().toString(); 
            if(boxsangre=="O RH+"){
              boxsangre="OP";
          } if(sexo=="O RH-"){
                boxsangre="ON";
          }if(boxsangre=="A RH+"){
                boxsangre="AP";
          }if(boxsangre=="A RH-"){
                boxsangre="AN";
          }if(boxsangre=="B RH+"){
                boxsangre="BP";
          }if(boxsangre=="B RH-"){
                boxsangre="BN";
          }if(boxsangre=="AB RH+"){
                boxsangre="ABP";
          }else if(boxsangre=="AB RH-"){
                boxsangre="ABN";
          }
       // String tiposangre = new String(jtiposangre.getText());
      d=new Donante(nombre,edad1,sexo,boxsangre);
                if(r.verificarDuplicado(d)){
                    JOptionPane.showMessageDialog(this,"ERROR, EL DONANTE YA EXISTE");
                  //  System.out.println("Error, el Donante ya existe");
                }else {
                    r.crear(d);
                }
        //r.crear(new Donante(nombre, edad1, sexo, boxsangre));
        
        jnombre.setText(null);
        jedad.setText(null);
       // jtiposangre.setText(null);
area.append(r.listar());
 }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos");
        }
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        try{ 
        String nombre = new String(jnombre.getText());
        String edad = new String(jedad.getText());
        Integer pos= new Integer(jpos.getText());
        Integer pos1=pos-1;
        int edad1 = Integer.parseInt(edad);
         v.vEdad(edad1);
        
               
          String sexo = selector.getSelectedItem().toString();  
          if(sexo=="Masculino"){
              sexo="H";
          }else if(sexo=="Femenino"){
              sexo="F";
          }
           String boxsangre = jsangre.getSelectedItem().toString(); 
            if(boxsangre=="O RH+"){
              boxsangre="OP";
          } if(boxsangre=="O RH-"){
                boxsangre="ON";
          }if(boxsangre=="A RH+"){
                boxsangre="AP";
          }if(boxsangre=="A RH-"){
                boxsangre="AN";
          }if(boxsangre=="B RH+"){
                boxsangre="BP";
          }if(boxsangre=="B RH-"){
                boxsangre="BN";
          }if(boxsangre=="AB RH+"){
                boxsangre="ABP";
          }else if(boxsangre=="AB RH-"){
                boxsangre="ABN";
          }
       // String tiposangre = new String(jtiposangre.getText());
      d=new Donante(nombre,edad1,sexo,boxsangre);
                if(r.verificarDuplicado(d)){
                    JOptionPane.showMessageDialog(this,"ERROR, EL DONANTE YA EXISTE");
                  //  System.out.println("Error, el Donante ya existe");
                }else {
                    r.actualizar(d,pos1);
                }
        //r.crear(new Donante(nombre, edad1, sexo, boxsangre));
                jpos.setText(null);

        jnombre.setText(null);
        jedad.setText(null);
       // jtiposangre.setText(null);
area.append(r.listar());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos");
        }
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
            area.append(r.listar());
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarDonante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarDonante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarDonante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarDonante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarDonante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jbutonguardar;
    private javax.swing.JTextField jedad;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jpos;
    private javax.swing.JComboBox<String> jsangre;
    private javax.swing.JComboBox<String> selector;
    // End of variables declaration//GEN-END:variables
}
